### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by mimansha-swarup**
## Landing Page
image

## Docs Page
image

### CODE REVIEW

**Review by vijaytembugade — APPROVED** [review]
Amazing colors and Logo. 
I dont know whether it is responsive or not, if not, you can add that.

**Comment by poornima-alugubelly** [comment]
Looks good Mimansha!

**Comment by horsemaker** [comment]
looks dope!

**Comment by preethasri** [comment]
looks great mimansha

**Review by jayeshjain98 — COMMENTED** [review]
looks good

**Pull request merged**
